// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFsriEylY7B2prHjt4aC_8UZdHBew1EaI',
    appId: '1:630457967108:web:e84eb934b990e3684a8b51',
    messagingSenderId: '630457967108',
    projectId: 'mytodoapp-8e3ce',
    authDomain: 'mytodoapp-8e3ce.firebaseapp.com',
    storageBucket: 'mytodoapp-8e3ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd-n_JZ_EoqhbUSWTN1vLsMwAaaaNie8s',
    appId: '1:630457967108:android:349bdabb6d9466414a8b51',
    messagingSenderId: '630457967108',
    projectId: 'mytodoapp-8e3ce',
    storageBucket: 'mytodoapp-8e3ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSL7s5yzw2DcIVkwl2n5_abd4KXGJxAy4',
    appId: '1:630457967108:ios:ebcbd599960c2d6d4a8b51',
    messagingSenderId: '630457967108',
    projectId: 'mytodoapp-8e3ce',
    storageBucket: 'mytodoapp-8e3ce.appspot.com',
    iosBundleId: 'com.rahul.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSL7s5yzw2DcIVkwl2n5_abd4KXGJxAy4',
    appId: '1:630457967108:ios:ebcbd599960c2d6d4a8b51',
    messagingSenderId: '630457967108',
    projectId: 'mytodoapp-8e3ce',
    storageBucket: 'mytodoapp-8e3ce.appspot.com',
    iosBundleId: 'com.rahul.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFsriEylY7B2prHjt4aC_8UZdHBew1EaI',
    appId: '1:630457967108:web:a918ba0da6b415254a8b51',
    messagingSenderId: '630457967108',
    projectId: 'mytodoapp-8e3ce',
    authDomain: 'mytodoapp-8e3ce.firebaseapp.com',
    storageBucket: 'mytodoapp-8e3ce.appspot.com',
  );
}
